### ISSUE TITLE
make failed on Linux (debian12)

### ISSUE THREAD

**Issue by thweasel** [oxidaan/zqloader#2]
Looks like you missed `#include <thread>` from samplesender.cpp.  Make errors with a message about sleep_for() not being a member.

**Make error reported:**

zqloader-0.9/samplesender.cpp:90:27: error: ‘sleep_for’ is not a member of ‘std::this_thread’
   90 |         std::this_thread::sleep_for(500ms); // otherwise stops before all data was send
      |                           ^~~~~~~~~
make[2]: *** [CMakeFiles/zqloader.dir/build.make:146: CMakeFiles/zqloader.dir/samplesender.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/zqloader.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**My solution was to add:**

*samplesender.cpp*
`#include <thread>`

**Comment by oxidaan** [comment]
Wow thanks, first issue ;-) I will check why I didn't get the same error, maybe gcc version is different. Obviously your fix is ok, will change soon!

**Comment by oxidaan** [comment]
Committed your suggestion, but I can not test it, it already compiled (using gcc version 9.4.0)
